import { LanguageCode } from './constants';

export type SearchMode = 'documents' | 'web' | 'combined';

export interface UITranslations {
  // Header
  intelligentQuery: string;
  queryDescription: string;
  
  // Search modes
  searchMode: string;
  documentsOnly: string;
  webOnly: string;
  combined: string;
  documentsOnlyDesc: string;
  webOnlyDesc: string;
  combinedDesc: string;
  
  // Chat interface
  startExploring: string;
  askAnyQuestion: string;
  askPlaceholder: string;
  clearConversation: string;
  
  // Loading states
  searchingKnowledgeBase: string;
  searchingWeb: string;
  
  // Web search prompt
  documentsNoInfo: string;
  wouldYouLikeWebSearch: string;
  searchTheWeb: string;
  searching: string;
  
  // Sources
  fromKnowledgeBase: string;
  webSources: string;
  
  // Errors
  errorTitle: string;
  rateLimitError: string;
  creditsExhausted: string;
  failedToProcess: string;
  webSearchFailed: string;
  webSearchComplete: string;
  foundInfoFromWeb: string;
  
  // Buttons
  send: string;
}

export const translations: Record<LanguageCode, UITranslations> = {
  en: {
    intelligentQuery: 'Intelligent',
    queryDescription: 'Ask questions about startup funding in your preferred language. Get grounded insights backed by real data sources.',
    searchMode: 'Search Mode',
    documentsOnly: 'Documents Only',
    webOnly: 'Web Only',
    combined: 'Combined',
    documentsOnlyDesc: 'Search only uploaded documents',
    webOnlyDesc: 'Search only the web',
    combinedDesc: 'Search documents first, then web',
    startExploring: 'Start Exploring',
    askAnyQuestion: 'Ask any question about startup funding, investors, or government policies',
    askPlaceholder: 'Ask your question here...',
    clearConversation: 'Clear conversation',
    searchingKnowledgeBase: 'Searching knowledge base...',
    searchingWeb: 'Searching the web...',
    documentsNoInfo: "Documents don't have the specific information you asked for.",
    wouldYouLikeWebSearch: 'Would you like to search the web for more up-to-date information?',
    searchTheWeb: 'Search the Web',
    searching: 'Searching...',
    fromKnowledgeBase: 'From Knowledge Base:',
    webSources: 'Web Sources:',
    errorTitle: 'Error',
    rateLimitError: 'Rate limit exceeded. Please try again in a moment.',
    creditsExhausted: 'AI credits exhausted. Please add credits to continue.',
    failedToProcess: 'Failed to process your query. Please try again.',
    webSearchFailed: 'Could not perform web search.',
    webSearchComplete: 'Web Search Complete',
    foundInfoFromWeb: 'Found information from the web!',
    send: 'Send',
  },
  hi: {
    intelligentQuery: 'बुद्धिमान',
    queryDescription: 'अपनी पसंदीदा भाषा में स्टार्टअप फंडिंग के बारे में सवाल पूछें। वास्तविक डेटा स्रोतों पर आधारित अंतर्दृष्टि प्राप्त करें।',
    searchMode: 'खोज मोड',
    documentsOnly: 'केवल दस्तावेज़',
    webOnly: 'केवल वेब',
    combined: 'संयुक्त',
    documentsOnlyDesc: 'केवल अपलोड किए गए दस्तावेज़ों में खोजें',
    webOnlyDesc: 'केवल वेब पर खोजें',
    combinedDesc: 'पहले दस्तावेज़ों में, फिर वेब पर खोजें',
    startExploring: 'खोज शुरू करें',
    askAnyQuestion: 'स्टार्टअप फंडिंग, निवेशकों, या सरकारी नीतियों के बारे में कोई भी प्रश्न पूछें',
    askPlaceholder: 'अपना प्रश्न यहाँ पूछें...',
    clearConversation: 'वार्तालाप साफ़ करें',
    searchingKnowledgeBase: 'ज्ञान आधार खोज रहा है...',
    searchingWeb: 'वेब पर खोज रहा है...',
    documentsNoInfo: 'दस्तावेज़ों में आपके द्वारा पूछी गई विशिष्ट जानकारी नहीं है।',
    wouldYouLikeWebSearch: 'क्या आप अधिक अद्यतित जानकारी के लिए वेब पर खोजना चाहेंगे?',
    searchTheWeb: 'वेब पर खोजें',
    searching: 'खोज रहा है...',
    fromKnowledgeBase: 'ज्ञान आधार से:',
    webSources: 'वेब स्रोत:',
    errorTitle: 'त्रुटि',
    rateLimitError: 'दर सीमा पार हो गई। कृपया थोड़ी देर बाद पुनः प्रयास करें।',
    creditsExhausted: 'AI क्रेडिट समाप्त। जारी रखने के लिए कृपया क्रेडिट जोड़ें।',
    failedToProcess: 'आपकी क्वेरी संसाधित करने में विफल। कृपया पुनः प्रयास करें।',
    webSearchFailed: 'वेब खोज नहीं कर सका।',
    webSearchComplete: 'वेब खोज पूर्ण',
    foundInfoFromWeb: 'वेब से जानकारी मिली!',
    send: 'भेजें',
  },
  ta: {
    intelligentQuery: 'புத்திசாலி',
    queryDescription: 'உங்கள் விருப்பமான மொழியில் ஸ்டார்ட்அப் நிதியுதவி பற்றி கேள்விகளைக் கேளுங்கள். உண்மையான தரவு மூலங்களால் ஆதரிக்கப்படும் நுண்ணறிவுகளைப் பெறுங்கள்.',
    searchMode: 'தேடல் முறை',
    documentsOnly: 'ஆவணங்கள் மட்டும்',
    webOnly: 'வெப் மட்டும்',
    combined: 'இணைந்த',
    documentsOnlyDesc: 'பதிவேற்றிய ஆவணங்களில் மட்டும் தேடுங்கள்',
    webOnlyDesc: 'வெப்பில் மட்டும் தேடுங்கள்',
    combinedDesc: 'முதலில் ஆவணங்கள், பின்னர் வெப்',
    startExploring: 'ஆராய்வைத் தொடங்குங்கள்',
    askAnyQuestion: 'ஸ்டார்ட்அப் நிதியுதவி, முதலீட்டாளர்கள் அல்லது அரசு கொள்கைகள் பற்றி எந்த கேள்வியும் கேளுங்கள்',
    askPlaceholder: 'உங்கள் கேள்வியை இங்கே கேளுங்கள்...',
    clearConversation: 'உரையாடலை அழி',
    searchingKnowledgeBase: 'அறிவுத்தளத்தில் தேடுகிறது...',
    searchingWeb: 'வெப்பில் தேடுகிறது...',
    documentsNoInfo: 'நீங்கள் கேட்ட குறிப்பிட்ட தகவல் ஆவணங்களில் இல்லை.',
    wouldYouLikeWebSearch: 'மேலும் புதுப்பித்த தகவலுக்கு வெப்பில் தேட விரும்புகிறீர்களா?',
    searchTheWeb: 'வெப்பில் தேடுங்கள்',
    searching: 'தேடுகிறது...',
    fromKnowledgeBase: 'அறிவுத்தளத்திலிருந்து:',
    webSources: 'வெப் மூலங்கள்:',
    errorTitle: 'பிழை',
    rateLimitError: 'வீத வரம்பு மீறப்பட்டது. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.',
    creditsExhausted: 'AI கிரெடிட்கள் தீர்ந்துவிட்டன. தொடர கிரெடிட்களைச் சேர்க்கவும்.',
    failedToProcess: 'உங்கள் வினவலைச் செயலாக்க இயலவில்லை. மீண்டும் முயற்சிக்கவும்.',
    webSearchFailed: 'வெப் தேடலைச் செய்ய முடியவில்லை.',
    webSearchComplete: 'வெப் தேடல் முடிந்தது',
    foundInfoFromWeb: 'வெப்பிலிருந்து தகவல் கிடைத்தது!',
    send: 'அனுப்பு',
  },
  te: {
    intelligentQuery: 'తెలివైన',
    queryDescription: 'మీ ఇష్టమైన భాషలో స్టార్టప్ ఫండింగ్ గురించి ప్రశ్నలు అడగండి. నిజమైన డేటా మూలాల ద్వారా ఆధారపడిన అంతర్దృష్టులను పొందండి.',
    searchMode: 'శోధన మోడ్',
    documentsOnly: 'పత్రాలు మాత్రమే',
    webOnly: 'వెబ్ మాత్రమే',
    combined: 'కలిపిన',
    documentsOnlyDesc: 'అప్‌లోడ్ చేసిన పత్రాలలో మాత్రమే శోధించండి',
    webOnlyDesc: 'వెబ్‌లో మాత్రమే శోధించండి',
    combinedDesc: 'ముందు పత్రాలు, తర్వాత వెబ్',
    startExploring: 'అన్వేషణ ప్రారంభించండి',
    askAnyQuestion: 'స్టార్టప్ ఫండింగ్, పెట్టుబడిదారులు లేదా ప్రభుత్వ విధానాల గురించి ఏదైనా ప్రశ్న అడగండి',
    askPlaceholder: 'మీ ప్రశ్నను ఇక్కడ అడగండి...',
    clearConversation: 'సంభాషణను క్లియర్ చేయండి',
    searchingKnowledgeBase: 'నాలెడ్జ్ బేస్‌లో శోధిస్తోంది...',
    searchingWeb: 'వెబ్‌లో శోధిస్తోంది...',
    documentsNoInfo: 'మీరు అడిగిన నిర్దిష్ట సమాచారం పత్రాలలో లేదు.',
    wouldYouLikeWebSearch: 'మరింత తాజా సమాచారం కోసం వెబ్‌లో శోధించాలనుకుంటున్నారా?',
    searchTheWeb: 'వెబ్‌లో శోధించండి',
    searching: 'శోధిస్తోంది...',
    fromKnowledgeBase: 'నాలెడ్జ్ బేస్ నుండి:',
    webSources: 'వెబ్ మూలాలు:',
    errorTitle: 'లోపం',
    rateLimitError: 'రేట్ పరిమితి మించిపోయింది. దయచేసి కొద్దిసేపట్లో మళ్ళీ ప్రయత్నించండి.',
    creditsExhausted: 'AI క్రెడిట్లు అయిపోయాయి. కొనసాగించడానికి దయచేసి క్రెడిట్లు జోడించండి.',
    failedToProcess: 'మీ ప్రశ్నను ప్రాసెస్ చేయడంలో విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    webSearchFailed: 'వెబ్ శోధన చేయలేకపోయింది.',
    webSearchComplete: 'వెబ్ శోధన పూర్తయింది',
    foundInfoFromWeb: 'వెబ్ నుండి సమాచారం కనుగొనబడింది!',
    send: 'పంపండి',
  },
  bn: {
    intelligentQuery: 'বুদ্ধিমান',
    queryDescription: 'আপনার পছন্দের ভাষায় স্টার্টআপ ফান্ডিং সম্পর্কে প্রশ্ন জিজ্ঞাসা করুন। প্রকৃত ডেটা উৎস দ্বারা সমর্থিত অন্তর্দৃষ্টি পান।',
    searchMode: 'অনুসন্ধান মোড',
    documentsOnly: 'শুধুমাত্র ডকুমেন্ট',
    webOnly: 'শুধুমাত্র ওয়েব',
    combined: 'সম্মিলিত',
    documentsOnlyDesc: 'শুধুমাত্র আপলোড করা ডকুমেন্টে অনুসন্ধান করুন',
    webOnlyDesc: 'শুধুমাত্র ওয়েবে অনুসন্ধান করুন',
    combinedDesc: 'প্রথমে ডকুমেন্ট, তারপর ওয়েব',
    startExploring: 'অন্বেষণ শুরু করুন',
    askAnyQuestion: 'স্টার্টআপ ফান্ডিং, বিনিয়োগকারী বা সরকারি নীতি সম্পর্কে যেকোনো প্রশ্ন জিজ্ঞাসা করুন',
    askPlaceholder: 'এখানে আপনার প্রশ্ন জিজ্ঞাসা করুন...',
    clearConversation: 'কথোপকথন মুছুন',
    searchingKnowledgeBase: 'জ্ঞান ভাণ্ডারে অনুসন্ধান করা হচ্ছে...',
    searchingWeb: 'ওয়েবে অনুসন্ধান করা হচ্ছে...',
    documentsNoInfo: 'আপনি যে নির্দিষ্ট তথ্য চেয়েছেন তা ডকুমেন্টে নেই।',
    wouldYouLikeWebSearch: 'আরও আপ-টু-ডেট তথ্যের জন্য ওয়েবে অনুসন্ধান করতে চান?',
    searchTheWeb: 'ওয়েবে অনুসন্ধান করুন',
    searching: 'অনুসন্ধান করা হচ্ছে...',
    fromKnowledgeBase: 'জ্ঞান ভাণ্ডার থেকে:',
    webSources: 'ওয়েব উৎস:',
    errorTitle: 'ত্রুটি',
    rateLimitError: 'রেট সীমা অতিক্রম করেছে। অনুগ্রহ করে কিছুক্ষণ পরে আবার চেষ্টা করুন।',
    creditsExhausted: 'AI ক্রেডিট শেষ। চালিয়ে যেতে অনুগ্রহ করে ক্রেডিট যোগ করুন।',
    failedToProcess: 'আপনার প্রশ্ন প্রক্রিয়া করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    webSearchFailed: 'ওয়েব অনুসন্ধান করা যায়নি।',
    webSearchComplete: 'ওয়েব অনুসন্ধান সম্পন্ন',
    foundInfoFromWeb: 'ওয়েব থেকে তথ্য পাওয়া গেছে!',
    send: 'পাঠান',
  },
  mr: {
    intelligentQuery: 'बुद्धिमान',
    queryDescription: 'तुमच्या आवडीच्या भाषेत स्टार्टअप फंडिंगबद्दल प्रश्न विचारा. खऱ्या डेटा स्रोतांवर आधारित अंतर्दृष्टी मिळवा.',
    searchMode: 'शोध मोड',
    documentsOnly: 'फक्त दस्तऐवज',
    webOnly: 'फक्त वेब',
    combined: 'एकत्रित',
    documentsOnlyDesc: 'फक्त अपलोड केलेल्या दस्तऐवजांमध्ये शोधा',
    webOnlyDesc: 'फक्त वेबवर शोधा',
    combinedDesc: 'आधी दस्तऐवज, मग वेब',
    startExploring: 'शोध सुरू करा',
    askAnyQuestion: 'स्टार्टअप फंडिंग, गुंतवणूकदार किंवा सरकारी धोरणांबद्दल कोणताही प्रश्न विचारा',
    askPlaceholder: 'तुमचा प्रश्न येथे विचारा...',
    clearConversation: 'संभाषण साफ करा',
    searchingKnowledgeBase: 'ज्ञान आधारात शोधत आहे...',
    searchingWeb: 'वेबवर शोधत आहे...',
    documentsNoInfo: 'तुम्ही विचारलेली विशिष्ट माहिती दस्तऐवजांमध्ये नाही.',
    wouldYouLikeWebSearch: 'अधिक अद्ययावत माहितीसाठी वेबवर शोधू इच्छिता?',
    searchTheWeb: 'वेबवर शोधा',
    searching: 'शोधत आहे...',
    fromKnowledgeBase: 'ज्ञान आधारातून:',
    webSources: 'वेब स्रोत:',
    errorTitle: 'त्रुटी',
    rateLimitError: 'दर मर्यादा ओलांडली. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.',
    creditsExhausted: 'AI क्रेडिट संपले. सुरू ठेवण्यासाठी कृपया क्रेडिट जोडा.',
    failedToProcess: 'तुमची क्वेरी प्रक्रिया करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    webSearchFailed: 'वेब शोध करता आला नाही.',
    webSearchComplete: 'वेब शोध पूर्ण',
    foundInfoFromWeb: 'वेबवरून माहिती मिळाली!',
    send: 'पाठवा',
  },
  gu: {
    intelligentQuery: 'બુદ્ધિશાળી',
    queryDescription: 'તમારી પસંદની ભાષામાં સ્ટાર્ટઅપ ફંડિંગ વિશે પ્રશ્નો પૂછો. વાસ્તવિક ડેટા સ્રોતો પર આધારિત આંતરદૃષ્ટિ મેળવો.',
    searchMode: 'શોધ મોડ',
    documentsOnly: 'માત્ર દસ્તાવેજો',
    webOnly: 'માત્ર વેબ',
    combined: 'સંયુક્ત',
    documentsOnlyDesc: 'માત્ર અપલોડ કરેલા દસ્તાવેજોમાં શોધો',
    webOnlyDesc: 'માત્ર વેબ પર શોધો',
    combinedDesc: 'પહેલા દસ્તાવેજો, પછી વેબ',
    startExploring: 'અન્વેષણ શરૂ કરો',
    askAnyQuestion: 'સ્ટાર્ટઅપ ફંડિંગ, રોકાણકારો અથવા સરકારી નીતિઓ વિશે કોઈપણ પ્રશ્ન પૂછો',
    askPlaceholder: 'તમારો પ્રશ્ન અહીં પૂછો...',
    clearConversation: 'વાતચીત સાફ કરો',
    searchingKnowledgeBase: 'જ્ઞાન આધારમાં શોધી રહ્યું છે...',
    searchingWeb: 'વેબ પર શોધી રહ્યું છે...',
    documentsNoInfo: 'તમે પૂછેલી ચોક્કસ માહિતી દસ્તાવેજોમાં નથી.',
    wouldYouLikeWebSearch: 'વધુ અપ-ટુ-ડેટ માહિતી માટે વેબ પર શોધવા માંગો છો?',
    searchTheWeb: 'વેબ પર શોધો',
    searching: 'શોધી રહ્યું છે...',
    fromKnowledgeBase: 'જ્ઞાન આધાર પરથી:',
    webSources: 'વેબ સ્રોતો:',
    errorTitle: 'ભૂલ',
    rateLimitError: 'દર મર્યાદા ઓળંગાઈ. કૃપા કરીને થોડી વાર પછી ફરી પ્રયાસ કરો.',
    creditsExhausted: 'AI ક્રેડિટ સમાપ્ત. ચાલુ રાખવા માટે કૃપા કરીને ક્રેડિટ ઉમેરો.',
    failedToProcess: 'તમારી ક્વેરી પ્રક્રિયા કરવામાં નિષ્ફળ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    webSearchFailed: 'વેબ શોધ કરી શકાઈ નહીં.',
    webSearchComplete: 'વેબ શોધ પૂર્ણ',
    foundInfoFromWeb: 'વેબ પરથી માહિતી મળી!',
    send: 'મોકલો',
  },
  kn: {
    intelligentQuery: 'ಬುದ್ಧಿವಂತ',
    queryDescription: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯಲ್ಲಿ ಸ್ಟಾರ್ಟ್‌ಅಪ್ ಫಂಡಿಂಗ್ ಬಗ್ಗೆ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ. ನಿಜವಾದ ಡೇಟಾ ಮೂಲಗಳಿಂದ ಬೆಂಬಲಿತ ಒಳನೋಟಗಳನ್ನು ಪಡೆಯಿರಿ.',
    searchMode: 'ಹುಡುಕಾಟ ಮೋಡ್',
    documentsOnly: 'ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳು ಮಾತ್ರ',
    webOnly: 'ವೆಬ್ ಮಾತ್ರ',
    combined: 'ಸಂಯೋಜಿತ',
    documentsOnlyDesc: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳಲ್ಲಿ ಮಾತ್ರ ಹುಡುಕಿ',
    webOnlyDesc: 'ವೆಬ್‌ನಲ್ಲಿ ಮಾತ್ರ ಹುಡುಕಿ',
    combinedDesc: 'ಮೊದಲು ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳು, ನಂತರ ವೆಬ್',
    startExploring: 'ಅನ್ವೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ',
    askAnyQuestion: 'ಸ್ಟಾರ್ಟ್‌ಅಪ್ ಫಂಡಿಂಗ್, ಹೂಡಿಕೆದಾರರು ಅಥವಾ ಸರ್ಕಾರಿ ನೀತಿಗಳ ಬಗ್ಗೆ ಯಾವುದೇ ಪ್ರಶ್ನೆ ಕೇಳಿ',
    askPlaceholder: 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಇಲ್ಲಿ ಕೇಳಿ...',
    clearConversation: 'ಸಂಭಾಷಣೆ ತೆರವುಗೊಳಿಸಿ',
    searchingKnowledgeBase: 'ಜ್ಞಾನ ಬೇಸ್‌ನಲ್ಲಿ ಹುಡುಕುತ್ತಿದೆ...',
    searchingWeb: 'ವೆಬ್‌ನಲ್ಲಿ ಹುಡುಕುತ್ತಿದೆ...',
    documentsNoInfo: 'ನೀವು ಕೇಳಿದ ನಿರ್ದಿಷ್ಟ ಮಾಹಿತಿ ಡಾಕ್ಯುಮೆಂಟ್‌ಗಳಲ್ಲಿ ಇಲ್ಲ.',
    wouldYouLikeWebSearch: 'ಹೆಚ್ಚು ನವೀಕೃತ ಮಾಹಿತಿಗಾಗಿ ವೆಬ್‌ನಲ್ಲಿ ಹುಡುಕಲು ಬಯಸುವಿರಾ?',
    searchTheWeb: 'ವೆಬ್‌ನಲ್ಲಿ ಹುಡುಕಿ',
    searching: 'ಹುಡುಕುತ್ತಿದೆ...',
    fromKnowledgeBase: 'ಜ್ಞಾನ ಬೇಸ್‌ನಿಂದ:',
    webSources: 'ವೆಬ್ ಮೂಲಗಳು:',
    errorTitle: 'ದೋಷ',
    rateLimitError: 'ದರ ಮಿತಿ ಮೀರಿದೆ. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    creditsExhausted: 'AI ಕ್ರೆಡಿಟ್‌ಗಳು ಖಾಲಿಯಾಗಿವೆ. ಮುಂದುವರಿಸಲು ದಯವಿಟ್ಟು ಕ್ರೆಡಿಟ್‌ಗಳನ್ನು ಸೇರಿಸಿ.',
    failedToProcess: 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    webSearchFailed: 'ವೆಬ್ ಹುಡುಕಾಟ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    webSearchComplete: 'ವೆಬ್ ಹುಡುಕಾಟ ಪೂರ್ಣ',
    foundInfoFromWeb: 'ವೆಬ್‌ನಿಂದ ಮಾಹಿತಿ ಕಂಡುಬಂದಿದೆ!',
    send: 'ಕಳುಹಿಸಿ',
  },
  ml: {
    intelligentQuery: 'ബുദ്ധിമാനായ',
    queryDescription: 'നിങ്ങൾ ഇഷ്ടപ്പെടുന്ന ഭാഷയിൽ സ്റ്റാർട്ടപ്പ് ഫണ്ടിംഗിനെക്കുറിച്ച് ചോദ്യങ്ങൾ ചോദിക്കുക. യഥാർത്ഥ ഡാറ്റ ഉറവിടങ്ങളാൽ പിന്തുണയ്ക്കുന്ന ഉൾക്കാഴ്ചകൾ നേടുക.',
    searchMode: 'തിരയൽ മോഡ്',
    documentsOnly: 'ഡോക്യുമെന്റുകൾ മാത്രം',
    webOnly: 'വെബ് മാത്രം',
    combined: 'സംയോജിത',
    documentsOnlyDesc: 'അപ്‌ലോഡ് ചെയ്ത ഡോക്യുമെന്റുകളിൽ മാത്രം തിരയുക',
    webOnlyDesc: 'വെബിൽ മാത്രം തിരയുക',
    combinedDesc: 'ആദ്യം ഡോക്യുമെന്റുകൾ, പിന്നെ വെബ്',
    startExploring: 'പര്യവേക്ഷണം ആരംഭിക്കുക',
    askAnyQuestion: 'സ്റ്റാർട്ടപ്പ് ഫണ്ടിംഗ്, നിക്ഷേപകർ അല്ലെങ്കിൽ സർക്കാർ നയങ്ങളെക്കുറിച്ച് ഏത് ചോദ്യവും ചോദിക്കുക',
    askPlaceholder: 'നിങ്ങളുടെ ചോദ്യം ഇവിടെ ചോദിക്കുക...',
    clearConversation: 'സംഭാഷണം മായ്ക്കുക',
    searchingKnowledgeBase: 'വിജ്ഞാനകോശത്തിൽ തിരയുന്നു...',
    searchingWeb: 'വെബിൽ തിരയുന്നു...',
    documentsNoInfo: 'നിങ്ങൾ ചോദിച്ച നിർദ്ദിഷ്ട വിവരങ്ങൾ ഡോക്യുമെന്റുകളിൽ ഇല്ല.',
    wouldYouLikeWebSearch: 'കൂടുതൽ അപ്‌ഡേറ്റ് ചെയ്ത വിവരങ്ങൾക്കായി വെബിൽ തിരയാൻ ആഗ്രഹിക്കുന്നുണ്ടോ?',
    searchTheWeb: 'വെബിൽ തിരയുക',
    searching: 'തിരയുന്നു...',
    fromKnowledgeBase: 'വിജ്ഞാനകോശത്തിൽ നിന്ന്:',
    webSources: 'വെബ് ഉറവിടങ്ങൾ:',
    errorTitle: 'പിശക്',
    rateLimitError: 'നിരക്ക് പരിധി കവിഞ്ഞു. ദയവായി കുറച്ച് സമയത്തിന് ശേഷം വീണ്ടും ശ്രമിക്കുക.',
    creditsExhausted: 'AI ക്രെഡിറ്റുകൾ തീർന്നു. തുടരാൻ ദയവായി ക്രെഡിറ്റുകൾ ചേർക്കുക.',
    failedToProcess: 'നിങ്ങളുടെ ചോദ്യം പ്രോസസ് ചെയ്യുന്നതിൽ പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
    webSearchFailed: 'വെബ് തിരയൽ നടത്താൻ കഴിഞ്ഞില്ല.',
    webSearchComplete: 'വെബ് തിരയൽ പൂർത്തിയായി',
    foundInfoFromWeb: 'വെബിൽ നിന്ന് വിവരങ്ങൾ കണ്ടെത്തി!',
    send: 'അയയ്ക്കുക',
  },
  pa: {
    intelligentQuery: 'ਬੁੱਧੀਮਾਨ',
    queryDescription: 'ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਵਿੱਚ ਸਟਾਰਟਅੱਪ ਫੰਡਿੰਗ ਬਾਰੇ ਸਵਾਲ ਪੁੱਛੋ। ਅਸਲ ਡਾਟਾ ਸਰੋਤਾਂ ਦੁਆਰਾ ਸਮਰਥਿਤ ਸੂਝ ਪ੍ਰਾਪਤ ਕਰੋ।',
    searchMode: 'ਖੋਜ ਮੋਡ',
    documentsOnly: 'ਸਿਰਫ਼ ਦਸਤਾਵੇਜ਼',
    webOnly: 'ਸਿਰਫ਼ ਵੈੱਬ',
    combined: 'ਸੰਯੁਕਤ',
    documentsOnlyDesc: 'ਸਿਰਫ਼ ਅੱਪਲੋਡ ਕੀਤੇ ਦਸਤਾਵੇਜ਼ਾਂ ਵਿੱਚ ਖੋਜੋ',
    webOnlyDesc: 'ਸਿਰਫ਼ ਵੈੱਬ ਤੇ ਖੋਜੋ',
    combinedDesc: 'ਪਹਿਲਾਂ ਦਸਤਾਵੇਜ਼, ਫਿਰ ਵੈੱਬ',
    startExploring: 'ਖੋਜ ਸ਼ੁਰੂ ਕਰੋ',
    askAnyQuestion: 'ਸਟਾਰਟਅੱਪ ਫੰਡਿੰਗ, ਨਿਵੇਸ਼ਕਾਂ ਜਾਂ ਸਰਕਾਰੀ ਨੀਤੀਆਂ ਬਾਰੇ ਕੋਈ ਵੀ ਸਵਾਲ ਪੁੱਛੋ',
    askPlaceholder: 'ਆਪਣਾ ਸਵਾਲ ਇੱਥੇ ਪੁੱਛੋ...',
    clearConversation: 'ਗੱਲਬਾਤ ਸਾਫ਼ ਕਰੋ',
    searchingKnowledgeBase: 'ਗਿਆਨ ਅਧਾਰ ਵਿੱਚ ਖੋਜ ਰਿਹਾ ਹੈ...',
    searchingWeb: 'ਵੈੱਬ ਤੇ ਖੋਜ ਰਿਹਾ ਹੈ...',
    documentsNoInfo: 'ਤੁਸੀਂ ਜੋ ਖਾਸ ਜਾਣਕਾਰੀ ਮੰਗੀ ਉਹ ਦਸਤਾਵੇਜ਼ਾਂ ਵਿੱਚ ਨਹੀਂ ਹੈ।',
    wouldYouLikeWebSearch: 'ਕੀ ਤੁਸੀਂ ਹੋਰ ਤਾਜ਼ਾ ਜਾਣਕਾਰੀ ਲਈ ਵੈੱਬ ਤੇ ਖੋਜ ਕਰਨਾ ਚਾਹੋਗੇ?',
    searchTheWeb: 'ਵੈੱਬ ਤੇ ਖੋਜੋ',
    searching: 'ਖੋਜ ਰਿਹਾ ਹੈ...',
    fromKnowledgeBase: 'ਗਿਆਨ ਅਧਾਰ ਤੋਂ:',
    webSources: 'ਵੈੱਬ ਸਰੋਤ:',
    errorTitle: 'ਗਲਤੀ',
    rateLimitError: 'ਦਰ ਸੀਮਾ ਪਾਰ ਹੋ ਗਈ। ਕਿਰਪਾ ਕਰਕੇ ਥੋੜੀ ਦੇਰ ਬਾਅਦ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    creditsExhausted: 'AI ਕ੍ਰੈਡਿਟ ਖਤਮ। ਜਾਰੀ ਰੱਖਣ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਕ੍ਰੈਡਿਟ ਜੋੜੋ।',
    failedToProcess: 'ਤੁਹਾਡੀ ਪੁੱਛਗਿੱਛ ਪ੍ਰਕਿਰਿਆ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    webSearchFailed: 'ਵੈੱਬ ਖੋਜ ਨਹੀਂ ਕਰ ਸਕਿਆ।',
    webSearchComplete: 'ਵੈੱਬ ਖੋਜ ਪੂਰੀ',
    foundInfoFromWeb: 'ਵੈੱਬ ਤੋਂ ਜਾਣਕਾਰੀ ਮਿਲੀ!',
    send: 'ਭੇਜੋ',
  },
};

export const getTranslation = (language: LanguageCode): UITranslations => {
  return translations[language] || translations.en;
};
